# Employee Management System - Docker Compose
# This file sets up PostgreSQL and Redis for local development
# Run with: docker compose up -d

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ems_postgres
    environment:
      POSTGRES_DB: ems_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ems_network

  # Redis for job queues
  redis:
    image: redis:7
    container_name: ems_redis
    ports:
      - "6379:6379"
    networks:
      - ems_network

volumes:
  postgres_data:

networks:
  ems_network:
    driver: bridge
